In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv("/content/creditcard.csv")

In [3]:
df.head(5)

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0     0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62    0.0
1     0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69    0.0
2     1 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66    0.0
3     1 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50    0.0
4     2 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [4]:
df.shape

(77338, 31)

In [5]:
df['Class'].value_counts()
#the databset is basically imbalanced here and we cant give this to the model as it is imbalanced

Class
0.0    77149
1.0      188
Name: count, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77338 entries, 0 to 77337
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    77338 non-null  int64
 1   V1      77338 non-null  float64
 2   V2      77338 non-null  float64
 3   V3      77338 non-null  float64
 4   V4      77338 non-null  float64
 5   V5      77338 non-null  float64
 6   V6      77338 non-null  float64
 7   V7      77338 non-null  float64
 8   V8      77338 non-null  float64
 9   V9      77338 non-null  float64
 10  V10     77338 non-null  float64
 11  V11     77338 non-null  float64
 12  V12     77338 non-null  float64
 13  V13     77338 non-null  float64
 14  V14     77337 non-null  float64
 15  V15     77337 non-null  float64
 16  V16     77337 non-null  float64
 17  V17     77337 non-null  float64
 18  V18     77337 non-null  float64
 19  V19     77337 non-null  float64
 20  V20     77337 non-null  float64
 21  V21     77337 non-null  float64
 22  V22     77337 non-null  float64
 23  V23     77337 non-null  float64
 24  V24     77337 non-null  float64
 25  V25     77337 non-null  float64
 26  V26     77337 non-null  float64
 27  V27     77337 non-null  float64
 28  V28     77337 non-null  float64
 29  Amount  77337 non-null  float64
 30  Class   77337 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 18.3 MB

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [8]:
df=df.dropna()

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77337 entries, 0 to 77336
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    77337 non-null  int64
 1   V1      77337 non-null  float64
 2   V2      77337 non-null  float64
 3   V3      77337 non-null  float64
 4   V4      77337 non-null  float64
 5   V5      77337 non-null  float64
 6   V6      77337 non-null  float64
 7   V7      77337 non-null  float64
 8   V8      77337 non-null  float64
 9   V9      77337 non-null  float64
 10  V10     77337 non-null  float64
 11  V11     77337 non-null  float64
 12  V12     77337 non-null  float64
 13  V13     77337 non-null  float64
 14  V14     77337 non-null  float64
 15  V15     77337 non-null  float64
 16  V16     77337 non-null  float64
 17  V17     77337 non-null  float64
 18  V18     77337 non-null  float64
 19  V19     77337 non-null  float64
 20  V20     77337 non-null  float64
 21  V21     77337 non-null  float64
 22  V22     77337 non-null  float64
 23  V23     77337 non-null  float64
 24  V24     77337 non-null  float64
 25  V25     77337 non-null  float64
 26  V26     77337 non-null  float64
 27  V27     77337 non-null  float64
 28  V28     77337 non-null  float64
 29  Amount  77337 non-null  float64
 30  Class   77337 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 18.9 MB

0 -->Normal Transaction

1 -->Fraudlent Transaction

In [10]:
legit=df[df.Class==0]
fraud=df[df.Class==1]

In [13]:
legit.Amount.describe()

count    77149.000000
mean        97.625867
std        270.623024
min          0.000000
25%          7.690000
50%         26.800000
75%         89.000000
max      19656.530000
Name: Amount, dtype: float64

In [14]:
fraud.Amount.describe()

count     188.000000
mean       94.292500
std       214.093799
min         0.000000
25%         1.000000
50%         7.550000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [15]:
#comare the values for both transacations
df.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28     Amount
Class                                    ...
0.0    36643.938353 -0.239252 -0.043518  ...  0.000766  0.002836  97.625867
1.0    32055.739362 -6.692335  4.711159  ...  0.586565  0.050794  94.292500

[2 rows x 30 columns]

In [20]:
#undersampling
legit_sample=legit.sample(n=188)

In [21]:
#concatenate the 2 datframes
new_df=pd.concat([legit_sample,fraud],axis=0)

In [22]:
new_df['Class'].value_counts()

Class
0.0    188
1.0    188
Name: count, dtype: int64

In [23]:
new_df.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0.0    38204.074468 -0.163259 -0.075056  ...  0.006902 -0.004157  108.626862
1.0    32055.739362 -6.692335  4.711159  ...  0.586565  0.050794   94.292500

[2 rows x 30 columns]

In [24]:
#splitting the data in features and target
X=new_df.drop(columns=['Class'],axis=1)
y=new_df['Class']

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2,stratify=y)

In [26]:
model=LogisticRegression()

In [27]:
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [28]:
X_test_pred=model.predict(X_test)
acc=accuracy_score(X_test_pred,y_test)
print(acc)

0.9342105263157895