In [3]:
import pandas as pd
import numpy as np
import difflib
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
df = pd.read_csv("/content/movies.csv", engine="python", on_bad_lines='skip')

In [5]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [6]:
df.shape

(197, 24)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 197 non-null    int64
 1   budget                197 non-null    int64
 2   genres                197 non-null    object
 3   homepage              150 non-null    object
 4   id                    197 non-null    int64
 5   keywords              195 non-null    object
 6   original_language     197 non-null    object
 7   original_title        197 non-null    object
 8   overview              197 non-null    object
 9   popularity            197 non-null    float64
 10  production_companies  197 non-null    object
 11  production_countries  197 non-null    object
 12  release_date          197 non-null    object
 13  revenue               197 non-null    int64
 14  runtime               197 non-null    float64
 15  spoken_languages      197 non-null    object
 16  status                197 non-null    object
 17  tagline               191 non-null    object
 18  title                 197 non-null    object
 19  vote_average          197 non-null    float64
 20  vote_count            197 non-null    int64
 21  cast                  197 non-null    object
 22  crew                  197 non-null    object
 23  director              197 non-null    object
dtypes: float64(3), int64(5), object(16)
memory usage: 37.1+ KB

In [8]:
df.isnull().sum()

index                    0
budget                   0
genres                   0
homepage                47
id                       0
keywords                 2
original_language        0
original_title           0
overview                 0
popularity               0
production_companies     0
production_countries     0
release_date             0
revenue                  0
runtime                  0
spoken_languages         0
status                   0
tagline                  6
title                    0
vote_average             0
vote_count               0
cast                     0
crew                     0
director                 0
dtype: int64

In [9]:
#selecting the relevant features for movie recommendation
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']

In [10]:
#replacing the null values with null strings
for i in selected_features:
  df[i]=df[i].fillna('')

In [11]:
#combinig all the 5 selected features
combined_features=df['genres']+''+df['keywords']+''+df['tagline']+''+df['cast']+''+df['director']

In [12]:
print(combined_features)

0      Action Adventure Fantasy Science Fictioncultur...
1      Adventure Fantasy Actionocean drug abuse exoti...
2      Action Adventure Crimespy based on novel secre...
3      Action Crime Drama Thrillerdc comics crime fig...
4      Action Adventure Science Fictionbased on novel...
                             ...
192    Dramamissionary world war ii ranch australia b...
193    Science Fiction Action AdventuredystopiaDanger...
194    Animation Familycataclysm asteroid leader come...
195    Adventure Comedy Fantasy Familynight watchman ...
196    Animation Action Comedy Family Science Fiction...
Length: 197, dtype: object

In [13]:
#converting the text data to numerical values
fe=TfidfVectorizer()

In [14]:
feature_vectors=fe.fit_transform(combined_features)

In [15]:
similarity=cosine_similarity(feature_vectors)

In [16]:
movie_name=input("enter your favourite movie name:")

enter your favourite movie name:iron man

In [17]:
list_of_all_titles=df['title'].tolist()

In [18]:
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [19]:
close_match=find_close_match[0]
print(close_match)

Iron Man

In [20]:
index_of_movie=df[df.title==close_match]['index'].values[0]

In [21]:
print(index_of_movie)

68

In [23]:
similarity_score=list(enumerate(similarity[index_of_movie]))
print(similarity_score)

[(0, np.float64(0.01130279860797617)), (1, np.float64(0.03868866406600617)), (2, np.float64(0.004504942711121175)), (3, np.float64(0.004552550705789916)), (4, np.float64(0.010468809780263778)), (5, np.float64(0.0042785947691879695)), (6, np.float64(0.07539864995633141)), (7, np.float64(0.1386368535281877)), (8, np.float64(0.0)), (9, np.float64(0.02273104554646778)), (10, np.float64(0.013083805623441903)), (11, np.float64(0.0037787594391085863)), (12, np.float64(0.0)), (13, np.float64(0.004219127570637983)), (14, np.float64(0.028491787882336254)), (15, np.float64(0.0)), (16, np.float64(0.17248373406826323)), (17, np.float64(0.004120800890700328)), (18, np.float64(0.010656411415852347)), (19, np.float64(0.0038486420888952104)), (20, np.float64(0.04036823806920797)), (21, np.float64(0.0036222674484456003)), (22, np.float64(0.0)), (23, np.float64(0.0)), (24, np.float64(0.0)), (25, np.float64(0.0)), (26, np.float64(0.14899505352256612)), (27, np.float64(0.010877377586617436)), (28, np.float64(0.060805509220854384)), (29, np.float64(0.004387513072237209)), (30, np.float64(0.04004266625420888)), (31, np.float64(0.2015127178630414)), (32, np.float64(0.033805221931222665)), (33, np.float64(0.08711177499906471)), (34, np.float64(0.0)), (35, np.float64(0.02865661310031591)), (36, np.float64(0.026400565331474505)), (37, np.float64(0.0)), (38, np.float64(0.061380185201895046)), (39, np.float64(0.0918250084274588)), (40, np.float64(0.0)), (41, np.float64(0.010618315378790943)), (42, np.float64(0.0)), (43, np.float64(0.026705456583607654)), (44, np.float64(0.0)), (45, np.float64(0.024800410791199577)), (46, np.float64(0.09652213082918389)), (47, np.float64(0.013125945712446276)), (48, np.float64(0.004826883487370346)), (49, np.float64(0.0)), (50, np.float64(0.004378236085003059)), (51, np.float64(0.02322523092451515)), (52, np.float64(0.023286363737426822)), (53, np.float64(0.0)), (54, np.float64(0.04275199080574908)), (55, np.float64(0.0)), (56, np.float64(0.013579217631921206)), (57, np.float64(0.04250391328747078)), (58, np.float64(0.0048996622707452265)), (59, np.float64(0.010800370162451077)), (60, np.float64(0.0)), (61, np.float64(0.026254630987368088)), (62, np.float64(0.004302747662320938)), (63, np.float64(0.0)), (64, np.float64(0.06363720455522923)), (65, np.float64(0.004209955499907194)), (66, np.float64(0.0)), (67, np.float64(0.007189327405748511)), (68, np.float64(1.0)), (69, np.float64(0.0)), (70, np.float64(0.0256772177602407)), (71, np.float64(0.004914192188347982)), (72, np.float64(0.011379869538772052)), (73, np.float64(0.0)), (74, np.float64(0.011880523386550986)), (75, np.float64(0.0)), (76, np.float64(0.043603755602186246)), (77, np.float64(0.0)), (78, np.float64(0.04220393940408248)), (79, np.float64(0.20824957703080807)), (80, np.float64(0.0)), (81, np.float64(0.00377030338231524)), (82, np.float64(0.026411988120863455)), (83, np.float64(0.028218404440569708)), (84, np.float64(0.0036696806847490455)), (85, np.float64(0.08122998721012234)), (86, np.float64(0.0)), (87, np.float64(0.00698843600499941)), (88, np.float64(0.004133170178866249)), (89, np.float64(0.0)), (90, np.float64(0.0)), (91, np.float64(0.07920106614581404)), (92, np.float64(0.0)), (93, np.float64(0.010972645103886878)), (94, np.float64(0.04258663271837244)), (95, np.float64(0.044353494060351044)), (96, np.float64(0.02431907115876708)), (97, np.float64(0.010420777243355089)), (98, np.float64(0.0)), (99, np.float64(0.003929392613849888)), (100, np.float64(0.0)), (101, np.float64(0.06529523941666349)), (102, np.float64(0.011572780682413231)), (103, np.float64(0.004185375287083313)), (104, np.float64(0.004461883877800003)), (105, np.float64(0.0)), (106, np.float64(0.0)), (107, np.float64(0.03106327722537791)), (108, np.float64(0.026329166984288936)), (109, np.float64(0.0)), (110, np.float64(0.02343441649217901)), (111, np.float64(0.024054105540350722)), (112, np.float64(0.003992680135686278)), (113, np.float64(0.0)), (114, np.float64(0.0)), (115, np.float64(0.0)), (116, np.float64(0.00999568844830597)), (117, np.float64(0.0)), (118, np.float64(0.0)), (119, np.float64(0.004229514343132774)), (120, np.float64(0.0)), (121, np.float64(0.003936350424453504)), (122, np.float64(0.03262003988113356)), (123, np.float64(0.010596435237374878)), (124, np.float64(0.0)), (125, np.float64(0.01115142742631537)), (126, np.float64(0.03919508559799557)), (127, np.float64(0.027456358814136966)), (128, np.float64(0.041232434741906215)), (129, np.float64(0.038890497389804754)), (130, np.float64(0.0)), (131, np.float64(0.04492048529813713)), (132, np.float64(0.0)), (133, np.float64(0.0)), (134, np.float64(0.004374361462273572)), (135, np.float64(0.0)), (136, np.float64(0.0)), (137, np.float64(0.0)), (138, np.float64(0.049546946884593865)), (139, np.float64(0.0038064723094801346)), (140, np.float64(0.004019617431236947)), (141, np.float64(0.0)), (142, np.float64(0.0)), (143, np.float64(0.0)), (144, np.float64(0.0)), (145, np.float64(0.0)), (146, np.float64(0.06112113841632652)), (147, np.float64(0.003829607111340362)), (148, np.float64(0.004231015772911991)), (149, np.float64(0.02477640133369363)), (150, np.float64(0.011080316250473905)), (151, np.float64(0.004231439718776668)), (152, np.float64(0.004117966531905864)), (153, np.float64(0.004026993727933972)), (154, np.float64(0.0)), (155, np.float64(0.0)), (156, np.float64(0.0032931114417556347)), (157, np.float64(0.0)), (158, np.float64(0.027485672247801525)), (159, np.float64(0.0)), (160, np.float64(0.003975359595843315)), (161, np.float64(0.0)), (162, np.float64(0.0)), (163, np.float64(0.023945525391429825)), (164, np.float64(0.007939080385034696)), (165, np.float64(0.012543487426412817)), (166, np.float64(0.030928766713425867)), (167, np.float64(0.004398690088237329)), (168, np.float64(0.011732878352832592)), (169, np.float64(0.030364238197225356)), (170, np.float64(0.024549959958168038)), (171, np.float64(0.0)), (172, np.float64(0.024402404474158736)), (173, np.float64(0.0)), (174, np.float64(0.06581499999468285)), (175, np.float64(0.0)), (176, np.float64(0.0)), (177, np.float64(0.0)), (178, np.float64(0.0)), (179, np.float64(0.0)), (180, np.float64(0.00412545535764556)), (181, np.float64(0.0)), (182, np.float64(0.05879983257138466)), (183, np.float64(0.011973448798382188)), (184, np.float64(0.02404686471774716)), (185, np.float64(0.04130365208610231)), (186, np.float64(0.003659270786246494)), (187, np.float64(0.003890540851076164)), (188, np.float64(0.004389050403830569)), (189, np.float64(0.0)), (190, np.float64(0.0)), (191, np.float64(0.0)), (192, np.float64(0.0)), (193, np.float64(0.02764135705859937)), (194, np.float64(0.0)), (195, np.float64(0.0)), (196, np.float64(0.011447756997023108))]

In [24]:
len(similarity_score)

197

In [26]:
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(68, np.float64(1.0)), (79, np.float64(0.20824957703080807)), (31, np.float64(0.2015127178630414)), (16, np.float64(0.17248373406826323)), (26, np.float64(0.14899505352256612)), (7, np.float64(0.1386368535281877)), (46, np.float64(0.09652213082918389)), (39, np.float64(0.0918250084274588)), (33, np.float64(0.08711177499906471)), (85, np.float64(0.08122998721012234)), (91, np.float64(0.07920106614581404)), (6, np.float64(0.07539864995633141)), (174, np.float64(0.06581499999468285)), (101, np.float64(0.06529523941666349)), (64, np.float64(0.06363720455522923)), (38, np.float64(0.061380185201895046)), (146, np.float64(0.06112113841632652)), (28, np.float64(0.060805509220854384)), (182, np.float64(0.05879983257138466)), (138, np.float64(0.049546946884593865)), (131, np.float64(0.04492048529813713)), (95, np.float64(0.044353494060351044)), (76, np.float64(0.043603755602186246)), (54, np.float64(0.04275199080574908)), (94, np.float64(0.04258663271837244)), (57, np.float64(0.04250391328747078)), (78, np.float64(0.04220393940408248)), (185, np.float64(0.04130365208610231)), (128, np.float64(0.041232434741906215)), (20, np.float64(0.04036823806920797)), (30, np.float64(0.04004266625420888)), (126, np.float64(0.03919508559799557)), (129, np.float64(0.038890497389804754)), (1, np.float64(0.03868866406600617)), (32, np.float64(0.033805221931222665)), (122, np.float64(0.03262003988113356)), (107, np.float64(0.03106327722537791)), (166, np.float64(0.030928766713425867)), (169, np.float64(0.030364238197225356)), (35, np.float64(0.02865661310031591)), (14, np.float64(0.028491787882336254)), (83, np.float64(0.028218404440569708)), (193, np.float64(0.02764135705859937)), (158, np.float64(0.027485672247801525)), (127, np.float64(0.027456358814136966)), (43, np.float64(0.026705456583607654)), (82, np.float64(0.026411988120863455)), (36, np.float64(0.026400565331474505)), (108, np.float64(0.026329166984288936)), (61, np.float64(0.026254630987368088)), (70, np.float64(0.0256772177602407)), (45, np.float64(0.024800410791199577)), (149, np.float64(0.02477640133369363)), (170, np.float64(0.024549959958168038)), (172, np.float64(0.024402404474158736)), (96, np.float64(0.02431907115876708)), (111, np.float64(0.024054105540350722)), (184, np.float64(0.02404686471774716)), (163, np.float64(0.023945525391429825)), (110, np.float64(0.02343441649217901)), (52, np.float64(0.023286363737426822)), (51, np.float64(0.02322523092451515)), (9, np.float64(0.02273104554646778)), (56, np.float64(0.013579217631921206)), (47, np.float64(0.013125945712446276)), (10, np.float64(0.013083805623441903)), (165, np.float64(0.012543487426412817)), (183, np.float64(0.011973448798382188)), (74, np.float64(0.011880523386550986)), (168, np.float64(0.011732878352832592)), (102, np.float64(0.011572780682413231)), (196, np.float64(0.011447756997023108)), (72, np.float64(0.011379869538772052)), (0, np.float64(0.01130279860797617)), (125, np.float64(0.01115142742631537)), (150, np.float64(0.011080316250473905)), (93, np.float64(0.010972645103886878)), (27, np.float64(0.010877377586617436)), (59, np.float64(0.010800370162451077)), (18, np.float64(0.010656411415852347)), (41, np.float64(0.010618315378790943)), (123, np.float64(0.010596435237374878)), (4, np.float64(0.010468809780263778)), (97, np.float64(0.010420777243355089)), (116, np.float64(0.00999568844830597)), (164, np.float64(0.007939080385034696)), (67, np.float64(0.007189327405748511)), (87, np.float64(0.00698843600499941)), (71, np.float64(0.004914192188347982)), (58, np.float64(0.0048996622707452265)), (48, np.float64(0.004826883487370346)), (3, np.float64(0.004552550705789916)), (2, np.float64(0.004504942711121175)), (104, np.float64(0.004461883877800003)), (167, np.float64(0.004398690088237329)), (188, np.float64(0.004389050403830569)), (29, np.float64(0.004387513072237209)), (50, np.float64(0.004378236085003059)), (134, np.float64(0.004374361462273572)), (62, np.float64(0.004302747662320938)), (5, np.float64(0.0042785947691879695)), (151, np.float64(0.004231439718776668)), (148, np.float64(0.004231015772911991)), (119, np.float64(0.004229514343132774)), (13, np.float64(0.004219127570637983)), (65, np.float64(0.004209955499907194)), (103, np.float64(0.004185375287083313)), (88, np.float64(0.004133170178866249)), (180, np.float64(0.00412545535764556)), (17, np.float64(0.004120800890700328)), (152, np.float64(0.004117966531905864)), (153, np.float64(0.004026993727933972)), (140, np.float64(0.004019617431236947)), (112, np.float64(0.003992680135686278)), (160, np.float64(0.003975359595843315)), (121, np.float64(0.003936350424453504)), (99, np.float64(0.003929392613849888)), (187, np.float64(0.003890540851076164)), (19, np.float64(0.0038486420888952104)), (147, np.float64(0.003829607111340362)), (139, np.float64(0.0038064723094801346)), (11, np.float64(0.0037787594391085863)), (81, np.float64(0.00377030338231524)), (84, np.float64(0.0036696806847490455)), (186, np.float64(0.003659270786246494)), (21, np.float64(0.0036222674484456003)), (156, np.float64(0.0032931114417556347)), (8, np.float64(0.0)), (12, np.float64(0.0)), (15, np.float64(0.0)), (22, np.float64(0.0)), (23, np.float64(0.0)), (24, np.float64(0.0)), (25, np.float64(0.0)), (34, np.float64(0.0)), (37, np.float64(0.0)), (40, np.float64(0.0)), (42, np.float64(0.0)), (44, np.float64(0.0)), (49, np.float64(0.0)), (53, np.float64(0.0)), (55, np.float64(0.0)), (60, np.float64(0.0)), (63, np.float64(0.0)), (66, np.float64(0.0)), (69, np.float64(0.0)), (73, np.float64(0.0)), (75, np.float64(0.0)), (77, np.float64(0.0)), (80, np.float64(0.0)), (86, np.float64(0.0)), (89, np.float64(0.0)), (90, np.float64(0.0)), (92, np.float64(0.0)), (98, np.float64(0.0)), (100, np.float64(0.0)), (105, np.float64(0.0)), (106, np.float64(0.0)), (109, np.float64(0.0)), (113, np.float64(0.0)), (114, np.float64(0.0)), (115, np.float64(0.0)), (117, np.float64(0.0)), (118, np.float64(0.0)), (120, np.float64(0.0)), (124, np.float64(0.0)), (130, np.float64(0.0)), (132, np.float64(0.0)), (133, np.float64(0.0)), (135, np.float64(0.0)), (136, np.float64(0.0)), (137, np.float64(0.0)), (141, np.float64(0.0)), (142, np.float64(0.0)), (143, np.float64(0.0)), (144, np.float64(0.0)), (145, np.float64(0.0)), (154, np.float64(0.0)), (155, np.float64(0.0)), (157, np.float64(0.0)), (159, np.float64(0.0)), (161, np.float64(0.0)), (162, np.float64(0.0)), (171, np.float64(0.0)), (173, np.float64(0.0)), (175, np.float64(0.0)), (176, np.float64(0.0)), (177, np.float64(0.0)), (178, np.float64(0.0)), (179, np.float64(0.0)), (181, np.float64(0.0)), (189, np.float64(0.0)), (190, np.float64(0.0)), (191, np.float64(0.0)), (192, np.float64(0.0)), (194, np.float64(0.0)), (195, np.float64(0.0))]

In [27]:
#printing the names of thr similar movies based on the index
print('Movie suggested for you :\n')
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=df[df.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_from_index)
    i+=1

Movie suggested for you :

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . The Avengers
5 . Captain America: Civil War
6 . Avengers: Age of Ultron
7 . X-Men: Days of Future Past
8 . TRON: Legacy
9 . X-Men: The Last Stand
10 . Captain America: The Winter Soldier
11 . Independence Day: Resurgence
12 . Tangled
13 . The Incredible Hulk
14 . X-Men: First Class
15 . X-Men: Apocalypse
16 . The Amazing Spider-Man 2
17 . Madagascar 3: Europe's Most Wanted
18 . Jurassic World
19 . Ant-Man
20 . The Last Airbender
21 . G-Force
22 . Interstellar
23 . G.I. Joe: The Rise of Cobra
24 . The Good Dinosaur
25 . Guardians of the Galaxy
26 . WALL·E
27 . The Jungle Book
28 . War of the Worlds
29 . Angels & Demons